services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: campusevent
    container_name: campusevent-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - campusevent
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: campusevent-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: campusevent
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: campusevent
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      retries: 5
      timeout: 10s
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks:
      - campusevent

  nginx:
    image: nginx:alpine
    container_name: campusevent-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - campusevent
    depends_on:
      - app

networks:
  campusevent:
    driver: bridge
