services:
  app:
    build:
      args:
        user: EventCampus
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: campusevent
    container_name: campusevent-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - campusevent

  nginx:
    image: nginx:alpine
    container_name: campusevent-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - campusevent
    depends_on:
      - app

networks:
  campusevent:
    driver: bridge
